"""empty message

Revision ID: 985dc7ec9397
Revises: 
Create Date: 2023-05-31 19:01:25.204311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985dc7ec9397'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_name', sa.String(), nullable=True),
    sa.Column('depot_number', sa.Integer(), nullable=True),
    sa.Column('in_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depots')
    # ### end Alembic commands ###
